services:
  grafana:
    image: grafana/grafana:11.5.2
    ports:
      - "3000:3000"
    volumes:
      - grafana:/var/lib/grafana
  prometheus:
    image: prom/prometheus:v3.2.1
    ports:
      - "9090:9090"
    volumes:
      - prometheus:/prometheus
      - /etc/infrastructure/prometheus:/etc/prometheus
volumes:
  grafana:
  prometheus:
