- hosts: raspberry_pi
  roles:
#    - role: prometheus.prometheus.prometheus
#      vars:
#        prometheus_version: 3.2.1

    - role: grafana.grafana.grafana
      vars:
        grafana_version: 11.5.2
        grafana_ini:
          security:
            admin_user: basil
            admin_password: basil
